name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full repository content is fetched

      # Debug: List repository contents
      - name: List repository contents
        run: ls -R

      # Run the include processor script
      # - name: Process Includes
      #   shell: pwsh
      #   run: |
      #     pwsh ./.github/workflows/includeProcessor.ps1 -path "Underware" -sharedFolderPath "Underware/shared/"

      # Get the files that have been changed in the PR
      - name: Get changed files
        id: changed-files-yaml
        uses: tj-actions/changed-files@v45
        with:
          files_yaml: |
            underware:
              - Underware/**

      # turn the changed files into an array
      # - name: Set changed files array
      #   id: set-changed-files-array
      #   run: |
      #     echo "::set-output name=underware_all_changed_files::$(echo ${{ steps.changed-files-yaml.outputs.underware.underware_all_changed_files }} | tr '\n' ' ')"
      #     echo "::set-output name=underware_any_changed::$(echo ${{ steps.changed-files-yaml.outputs.underware }} | wc -l)"

      - name: Set changed files array
        id: set-changed-files-array
        shell: pwsh
        run: |
          $changedFiles = "${{ steps.changed-files-yaml.outputs.underware.underware_all_changed_files }}"
          $filesArray = if ([string]::IsNullOrWhiteSpace($changedFiles)) { 
            @() 
          } else { 
            $changedFiles.Split(',').Trim() 
          }
          $filesArrayString = $filesArray -join ','
          Write-Output "::set-output name=underware_all_changed_files::$filesArrayString"
          Write-Host "Changed files: $($filesArray.Count)"

      # Run the include processor script
      - name: Process SCAD
        id: process-scad
        if: steps.changed-files-yaml.outputs.underware_any_changed == 'true'
        env:
          UNDERWARE_ALL_CHANGED_FILES: ${{ steps.set-changed-files-array.outputs.underware_all_changed_files }}
        shell: pwsh
        run: |
            pwsh ./.github/workflows/scripts/scad/scad-include-processor.ps1 -pathArray ${UNDERWARE_ALL_CHANGED_FILES}

      # Upload the /underware folder as an artifact. Run only if process-scad has run
      - name: Upload underware folder
        uses: actions/upload-artifact@v4
        if: steps.process-scad.outcome == 'success'
        with:
          name: underware-artifacts
          path: Underware/output
